-- Bulk-load inicial de leads (Hot List).
-- Pegar y ejecutar en Supabase SQL Editor.
--
-- Notas:
--  - Sólo usa columnas existentes en `leads` (name, source, lead_type, rating,
--    instagram, niche, notes, created_at, status). No crea columnas nuevas.
--  - Fechas ausentes → 2025-12-15 (antes de los leads existentes en el dashboard).
--  - Status default = 'nuevo'.
--  - Los nombres con duplicados (Laura Marquez, Maikol Camacho) ya están deduplicados.
--  - La fila huérfana "5" sin nombre fue descartada.
--
-- Si querés deshacerlo:
--   delete from public.leads where created_at <= '2026-02-22' and source in ('Instagram DM','Youtube','Ready');

insert into public.leads (name, source, lead_type, rating, instagram, niche, notes, created_at, status) values
-- ── Rating 5 (Inbound - Directo) ────────────────────────────────────────────
('Del Caos al Orden Jose',  'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/soymentor/',                                    'Personal Development', 'hacer follow up febrero',                                                                                                              '2026-01-06', 'nuevo'),
('Tania Mora',              'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/106440394086387/',                     'Business',             'Lead vieja que no se sentia lista pero ahora se ve mucho mas consciente',                                                              '2025-12-15', 'nuevo'),
('Nicolas Becerra',         'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/103328727734052/',                     'Business',             'Dijo que queria entrar en febrero',                                                                                                    '2026-02-01', 'nuevo'),
('Manu Llaguno',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/110182363709514/',                     'Personal Development', 'Dejo 200 de seña para ingresar en febrero',                                                                                            '2026-02-01', 'nuevo'),
('Laura Marquez',           'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/119651856092890/',                     'Other',                'No tiene la plata ahora hacer follow up',                                                                                              '2025-12-15', 'nuevo'),
('Miguel Portocarrero',     'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/107326617326078/',                     'Business',             'Ya se vio todo el contenido, vio el doc con el precio, ya esta listo para arrancar basicamente. Dice que nuestra oferta es lo que necesita. Tiene mucho flow de leads pero la mayoria son de poca calidad.', '2025-12-15', 'nuevo'),
('Laura Ojinaga',           'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17847203646597258/',                   'Personal Development', 'ya se envio la offer doc con precio hacer follow up',                                                                                  '2025-12-15', 'nuevo'),
('Andres Gomez',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/103141724419219/',                     'Health & Fitness',     'Vino inbound y recibio la offer doc sin precio',                                                                                       '2025-12-15', 'nuevo'),
('Lucia Rodriguez',         'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/lurodriguezterapia',                            'Personal Development', 'Calificar y enviar offer doc',                                                                                                         '2026-02-22', 'nuevo'),
('Gio',                     'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/gio_delapaz/',                                  null,                   'offer doc enviado',                                                                                                                    '2025-12-15', 'nuevo'),
('Susy Umaña',              'Instagram DM', 'Inbound - Directo', 5, 'wapp',                                                                    'Personal Development', 'offer doc enviado',                                                                                                                    '2025-12-15', 'nuevo'),
('Nathali Vega',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17845202721490913/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Francisca',               'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/18055176533481502/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Jean Mendez',             'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17850792818609542/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Sebastian Quezadas',      'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/106931487364167/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Pablo Moyano',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/112179250181023/',                     'Health & Fitness',     'seguimiento 30 de marzo',                                                                                                              '2025-12-15', 'nuevo'),
('Vicente Delgado',         'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/109682187093163',                      'Health & Fitness',     'seguimiento 20 de abril',                                                                                                              '2025-12-15', 'nuevo'),
('Gabriel',                 'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/',                                              'Personal Development', 'Timing',                                                                                                                                '2025-12-15', 'nuevo'),
('Esteban Martinez',        'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/120906152632223/',                     'Personal Development', null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Nico Agencia',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/nicons__/',                                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Miguel Angel',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/119703656084235/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Esteban 8aa',             'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/118928146160705/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Gaston Aldana',           'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17844530162499456/',                   'Personal Development', null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Jesse Samuel',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/mccallumsworldwide/',                           'Personal Development', 'follow up',                                                                                                                            '2025-12-15', 'nuevo'),
('Bryan Padilla',           'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/107416740655109/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Raphjorge',               'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/raphjorge/',                                    null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Martin Montequin',        'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/116417676417139/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Diego Gonzales',          'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17848930332267649/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Jesus Moreno',            'Instagram DM', 'Inbound - Directo', 5, 'https://www.instagram.com/direct/t/17847308010544312/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),

-- ── Rating 4 (Inbound - Directo) ────────────────────────────────────────────
('John Prime',              'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/101074117959714/',                     'Business',             'Contactar en febrero',                                                                                                                 '2026-01-13', 'nuevo'),
('Jaffet Gallardo',         'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/106508590746394/',                     'Finanzas',             'Cerrar',                                                                                                                                '2026-01-13', 'nuevo'),
('Ulises Records',          'Instagram DM', 'Inbound - Directo', 4, null,                                                                      'Business',             'Super responsivo pero dice que quiere arreglar su problema ahora pero como que no es buen timing',                                     '2026-01-23', 'nuevo'),
('Franco Amable',           'Instagram DM', 'Inbound - Directo', 4, null,                                                                      'Health & Fitness',     null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Paolo Cavalleri',         'Instagram DM', 'Inbound - Directo', 4, null,                                                                      'Business',             null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Sebastián Saldía',        null,           null,                4, null,                                                                      null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Pato Rojas',              'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/findyour.breath',                               'Personal Development', 'Timing hacer follow up',                                                                                                                '2025-12-15', 'nuevo'),
('Maikol Camacho',          'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/maicol.camacho7',                               'Business',             null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Tomas Jorge',             'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/tomijorge',                                     'Personal Development', null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Julian Gonzales',         'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/111757830210000/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Alejo Bozzoli',           'Instagram DM', 'Inbound - Directo', 4, 'https://airtable.com/appLi93JF4oW6DzvN/tbluX5bFqT9k3ZBPn',                null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Marc Arbones',            'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/marc.arbones/',                                 null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Nico Vonr',               'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/111714740225612/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Moises Moyayo',           'Youtube',      'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/17843368044305094/',                   null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('Antonio Labarta',         'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/106380927428712/',                     null,                   null,                                                                                                                                   '2025-12-15', 'nuevo'),
('leonardo.assennato',      'Instagram DM', 'Inbound - Directo', 4, 'https://www.instagram.com/direct/t/17844876983622415/',                   'Personal Development', 'follow up',                                                                                                                            '2025-12-15', 'nuevo'),

-- ── Sin rating (Inbound - Directo) ──────────────────────────────────────────
('Vanessa Shapiro',         'Instagram DM', 'Inbound - Directo', null, 'https://www.instagram.com/direct/t/108880867174274/',                  'Personal Development', null,                                                                                                                                   '2025-12-15', 'nuevo'),

-- ── Outbound ─────────────────────────────────────────────────────────────────
('Patricio Rojas',          'Instagram DM', 'Outbound',          5,    null,                                                                   null,                   'checked',                                                                                                                              '2025-12-15', 'nuevo'),

-- ── Ready (research / pipeline pre-outreach) ────────────────────────────────
('Andrés Gómez | Médico',                                                   'Ready',   null, null, 'drgomezq',                  null, null, '2026-02-09', 'nuevo'),
('Temo Valle | Activos de Valor | Marca Privada',                           'Ready',   null, null, 'activosdevalor',            null, null, '2026-02-10', 'nuevo'),
('Ann Sahakyan',                                                            'Ready',   null, null, 'anisahakyan.us',            null, null, '2026-02-10', 'nuevo'),
('Fede Blumberg',                                                           'Ready',   null, null, 'fedeblum',                  null, null, '2026-02-10', 'nuevo'),
('Lisandro Allende | Manager de Infoproductos',                             'Youtube', null, null, 'lisandroallende.mkt',       null, null, '2026-02-13', 'nuevo'),
('Jean',                                                                    'Ready',   null, null, 'eujeangommes',              null, null, '2026-02-13', 'nuevo'),
('Estudio Mutsimu',                                                         'Youtube', null, null, 'estudio_mutsimu',           null, null, '2026-02-14', 'nuevo'),
('Matias Santoro | Brand Partners',                                         'Youtube', null, null, 'matiassantoromkt',          null, null, '2026-02-14', 'nuevo'),
('Estefi Batistón',                                                         'Youtube', null, null, 'estefi.batiston',           null, null, '2026-02-15', 'nuevo'),
('María Gómez',                                                             'Youtube', null, null, 'mariag0f',                  null, null, '2026-02-16', 'nuevo'),
('Juan Aurelio Zarate Maldonado',                                           'Youtube', null, null, 'juanaureliozaratemaldonado',null, null, '2026-02-16', 'nuevo'),
('ser',                                                                     'Youtube', null, null, 'sergio.calz',               null, null, '2026-02-16', 'nuevo'),
('Beñat Arrieta',                                                           'Youtube', null, null, 'benat.arrieta',             null, null, '2026-02-17', 'nuevo'),
('Rodrigo San Martin',                                                      'Youtube', null, null, 'rodrigosanmartinprofe',     null, null, '2026-02-17', 'nuevo'),
('Mari',                                                                    'Youtube', null, null, 'emprendeconmarianna',       null, null, '2026-02-18', 'nuevo'),
('Aleyda Bojorquez',                                                        'Ready',   null, null, 'aleyda.boo',                null, null, '2026-02-18', 'nuevo'),
('Malcolm Ugalde | Inversiones',                                            'Ready',   null, null, 'malcolmugalde',             null, null, '2026-03-05', 'nuevo'),
('Justo',                                                                   'Ready',   null, null, 'justo_helbert',             null, null, '2026-03-06', 'nuevo'),
('Maritza Castro | Especialista en Glúteos & Pérdida de grasa',             'Ready',   null, null, 'mar.fitness__',             null, null, '2026-03-06', 'nuevo'),
('Julio Olivo',                                                             'Ready',   null, null, 'julio.olivo95',             null, null, '2026-03-07', 'nuevo'),
('Mariana',                                                                 'Ready',   null, null, 'marianamrco',               null, null, '2026-03-07', 'nuevo'),
('Ezequiel Velazquez',                                                      'Ready',   null, null, 'eze_velz',                  null, null, '2026-03-09', 'nuevo'),
('Yese',                                                                    'Ready',   null, null, 'jeeselu15',                 null, null, '2026-03-09', 'nuevo'),
('House Of Motion | Agency · La Casa Del Movimiento',                       'Ready',   null, null, 'houseofmotion.col',         null, null, '2026-03-10', 'nuevo'),
('Karen Varcal',                                                            'Ready',   null, null, 'karenvarcal',               null, null, '2026-03-10', 'nuevo'),
('Ayelén Bravo Aravena',                                                    'Ready',   null, null, 'ayelen.bravoa',             null, null, '2026-03-12', 'nuevo'),
('Camal Sánchez | Directora Creativa Holística',                            'Ready',   null, null, 'soycreativecamal',          null, null, '2026-03-13', 'nuevo'),
('Jeanca Méndez',                                                           'Ready',   null, null, 'jeankmc',                   null, null, '2026-03-14', 'nuevo'),
('Héctor Abad Santaella',                                                   'Ready',   null, null, '_hectorabad_',              null, null, '2026-03-14', 'nuevo'),
('Maria',                                                                   'Ready',   null, null, 'mariaepica8',               null, null, '2026-03-14', 'nuevo'),
('Luis Enrique AS',                                                         'Ready',   null, null, 'luis_aguilar059',           null, null, '2026-03-15', 'nuevo'),
('carlosandres.vs',                                                         'Ready',   null, null, 'carlosandres.vs',           null, null, '2026-03-16', 'nuevo'),
('Edgardo RMG',                                                             'Ready',   null, null, 'edgardormg',                null, null, '2026-03-16', 'nuevo'),
('Yeremy M',                                                                'Ready',   null, null, 'yefebsm_',                  null, null, '2026-03-16', 'nuevo'),
('Jessica Muñoz',                                                           'Ready',   null, null, 'jessimunozv',               null, null, '2026-03-18', 'nuevo'),
('Andrea Minatta',                                                          'Ready',   null, null, 'andreaminatta',             null, null, '2026-03-19', 'nuevo');
